### ISSUE TITLE
[ website ] bug that show horizontal bar on edge

### ISSUE THREAD

**Issue by MisileLab** [aspen-cloud/triplit#133]
![image](https://github.com/aspen-cloud/triplit/assets/74066467/50fe4ac4-1e36-43e4-b9cc-579bf4398810)

**Comment by Ayusht777** [comment]
if open than i want to fix this issue

**Comment by matlin** [comment]
Doesn't seem to be the case anymore so closing but feel free to re-open if you still seen this.
