### ISSUE TITLE
Request: dont make me manually migrate my database on each restart during local development

### ISSUE THREAD

**Issue by wernst** [aspen-cloud/triplit#16]
When you run `triplit dev` your database server starts. Although the `storage` option is available to specify more persistent storage (like sqlite) it is not the default, instead the database will start with en empty in-memory storage instance.

Because the db starts empty, your migrations aren't tracked on the remote database and that can cause some small issues or features to not run (like authz).

From a pure ux perspective its tough to remember to run these migrations and I have to switch to a different terminal window to run them.

Suggestions:
- Run your local migrations when starting the triplit dev server
- When dev runs, if there are unapplied migrations, suggest that i run them
- larger refactor surrounding how schemas/migrations are applied in local development

**Comment by matlin** [comment]
You can start your dev server like `triplit dev --init-with-schema` that will apply your schema to the server at startup.
Docs here: https://www.triplit.dev/docs/getting-started#syncing-in-local-development
