### ISSUE TITLE
npm create triplit-app has network issues

### ISSUE THREAD

**Issue by tkoop** [aspen-cloud/triplit#167]
I ran this:
```bash
npm create triplit-app
```
I picked Vue and called the project triplit3
```
cd triplit3
npm install
npm run dev
```
This started the local server, but when I went to http://localhost:5173/ the page showed it was offline, and the JavaScript console showed this:

![image](https://github.com/user-attachments/assets/f47fc7f1-230b-4b05-b488-fac6ea701c7c)

**Comment by wernst** [comment]
There should be some additional instructions on that page. I can see how one might miss that as it's not in the CLI output. Did you run `npx triplit dev`? That should run a local development server at `localhost:6543` which the Triplit client should connect to.

**Comment by tkoop** [comment]
Yup, `npx triplit dev` fixed it. Thanks.

I agree that this should be mentioned on that page.
