### ISSUE TITLE
Make connection errors more accessible

### ISSUE THREAD

**Issue by wernst** [aspen-cloud/triplit#17]
Although I can hook into the connection state, I don't have much information as to WHY a client cannot connect.

For example, I may have a malformed connection token, but have no way to pull this specific error information out of the client or react packages.

Without providing this, the app can really only inform the user the app is disconnected, but not what it could do about it (or if it expects that it may be able to reconnect).

**Comment by pbohlman** [comment]
Closing with the addition of onSessionError https://www.triplit.dev/docs/client/sessions#onsessionerror
