### ISSUE TITLE
Self-hosted server via Docker crashes when a collection is named "users"

### ISSUE THREAD

**Issue by jkoop** [aspen-cloud/triplit#175]
```plain
triplit-app-1  | Node.js v20.16.0
triplit-app-1  | 
triplit-app-1  | > node-server@0.3.68 start
triplit-app-1  | > node ./run.js
triplit-app-1  | 
triplit-app-1  | running on port 8080
triplit-app-1  | ℹ ⬅ TRIPLES_REQUEST 
triplit-app-1  | ℹ ➡ TRIPLES_PENDING 
triplit-app-1  | ℹ ⬅ TRIPLES_REQUEST 
triplit-app-1  | ℹ ➡ CONNECT_QUERY 
triplit-app-1  | ℹ ➡ CONNECT_QUERY 
triplit-app-1  | ℹ ⬅ TRIPLES sent 0 triple(s)
triplit-app-1  | file:///app/node_modules/@triplit/db/dist/query/prepare.js:70
triplit-app-1  |             throw new InvalidCollectionNameError(collectionName, `Collection '${collectionName}' does not exist in the schema`);
triplit-app-1  |                   ^
triplit-app-1  | 
triplit-app-1  | InvalidCollectionNameError: users is not a valid collection name. | Context: Collection 'users' does not exist in the schema
triplit-app-1  |     at validateCollectionName (file:///app/node_modules/@triplit/db/dist/query/prepare.js:70:19)
triplit-app-1  |     at prepareQuery (file:///app/node_modules/@triplit/db/dist/query/prepare.js:12:5)
triplit-app-1  |     at startSubscription (file:///app/node_modules/@triplit/db/dist/db.js:377:37)
triplit-app-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
triplit-app-1  |   status: 400,
triplit-app-1  |   baseMessage: 'users is not a valid collection name.',
triplit-app-1  |   contextMessage: "Collection 'users' does not exist in the schema",
triplit-app-1  |   __isTriplitError: true
triplit-app-1  | }
triplit-app-1  | 
```
[database.sqlite.gz](https://github.com/user-attachments/files/16446370/database.sqlite.gz)

**Comment by wernst** [comment]
An error like this indicates the server isn't aware of a collection called `users`.

You can view your server's schema with our CLI by running `triplit schema print`. That should help confirm the state of the server schema. If it doesn't have a users collection, but you have one defined in your local schema file, you'll need to run `triplit schema push` to update the server schema. You can then confirm the stored schema with `triplit schema print`.

If it still doesnt seem like to work, try restarting your server (if it comes to that let us know).

**Comment by wernst** [comment]
Also thanks for the db output, will check that out as well

**Comment by jkoop** [comment]
There is no schema file. What I did was I created a project on triplit.dev and set up a self-hosted triplit server and got the triplit.dev console talking to the triplit server (the documentation for this is poor, but that's not in scope here). Then, with the console, I created a collection called "friends", then a collection called "users", then the server crashed and exited. `dockerd` then restarts it over and over, and it crashes and crashes.

**Comment by wernst** [comment]
Appreciate the extra info. Going to try to recreate this. We should protect against "expected" errors (like this one) causing a hard crash of the server, but seems like it might be slipping though. Are there any more logs with errors?

**Comment by jkoop** [comment]
No, that's all I have. Sorry

**Comment by wernst** [comment]
No worries, will report back soon

**Comment by wernst** [comment]
Ive been able to recreate this. Sorry you ran into that, but we appreciate you reporting it! Working on a fix for you now.

**Comment by wernst** [comment]
Hi @jkoop try updating your image to the latest version `0.3.70`, that should contain some fixes. There were two issues afoot here.
(1) There was a race condition causing a subscription (subscribing to data in your new collection) to initialize prior to the updated collection being available on the server
(2) this would have quickly resolved itself on its own (it would logged an error), but the error being thrown was sneaking through and not being caught in this specific case, causing the server to crash. The console tab being open (I think) probably was causing the continuous crashing.


If you're still having issues we'll reopen.
