### ISSUE TITLE
Can't connect to https://console.triplit.dev/local with Safari or Brave

### ISSUE THREAD

**Issue by ninjaPixel** [aspen-cloud/triplit#188]
Hey, folks! I'm just trying out Triplit, following the [Quick Start](https://www.triplit.dev/docs/quick-start). The client-side todo app is running and the local Triplit server is running (`npx triplit dev`), all looks good.

However, when I visit https://console.triplit.dev/local from Safari or Brave it's always "connecting" in the top left. There is a WebSocket error in the browser console. This seems to be a browser issue and can be fixed in Brave by turning off "shields" (I'm not sure what the Safari solution is).

I just thought I'd make you aware of this incase there is a way to surface a useful error message to the user in this situation.

Thanks for building such a cool product! ✌️

Brave:
<img width="1331" alt="Screenshot 2024-08-11 at 17 10 43" src="https://github.com/user-attachments/assets/3e13b715-811f-4093-a563-b6d9844435e6">

Shields down fixes it for Brave:
<img width="750" alt="Screenshot 2024-08-11 at 17 18 19" src="https://github.com/user-attachments/assets/26a2a515-7b8a-4eae-bd72-a866e7d94ebe">
 

Safari:
<img width="879" alt="Screenshot 2024-08-11 at 17 15 34" src="https://github.com/user-attachments/assets/ab4cc464-8b91-4269-b332-2dbd81ccc5fa">

**Comment by pbohlman** [comment]
Thanks for alerting us to this. The console app is served over HTTPS but attempts to connect to your local Triplit development server running on `localhost:6543` over HTTP. This is an instance of [mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content), and is generally blocked by browsers. Localhost is usually treated as an exception to the rule and permitted, however, it is not allowed by default in either Safari or Brave. [Caniuse table for additional reference](https://caniuse.com/mdn-http_mixed-content_allow_localhost_url).

As you've identified, you can disable the Brave shield, or, [according to a blog they released](https://brave.com/privacy-updates/27-localhost-permission/#fn:2), update your browser settings to put the console on a whitelist to allow content access from localhost. I haven't come across a workaround on Safari, which doesn't seem to offer these same configuration options. In the future we might look into making the `/local` endpoint  configurable to connect over https/wss, which would involve the developer setting up [HTTPS for local development](https://web.dev/articles/how-to-use-local-https). 

Closing this for now.
