### ISSUE TITLE
Vanilla JS

### ISSUE THREAD

**Issue by SantoshSrinivas79** [aspen-cloud/triplit#213]
Hello, Is it possible to use triplit with Vanilla JS? (No react, vite, etc)

**Comment by matlin** [comment]
Absolutely! You can just use the [@triplit/client](https://www.npmjs.com/package/@triplit/client) package by itself.

**Comment by SantoshSrinivas79** [comment]
Great! Can I please get an example that can give me enough sample code of few transaction types to get started? 🙏  ... plain vanilla html + js
