### ISSUE TITLE
0.5.x breaks demo project (stuck on Loading...)

### ISSUE THREAD

**Issue by patrr2** [aspen-cloud/triplit#218]
React demo project is broken in the latest version, it's stuck on 'Loading...'.

**Comment by matlin** [comment]
Just tested and it seems to be working. Can you clarify which demo project you mean?

Also would be helpful to know your Node version, package manager, OS, etc.

**Comment by patrr2** [comment]
Hi, thank you for the response! I didn't realise it's not broken for everyone.

The demo project is the latest one in `template/react`. I made it using `pnpm create triplit-app@latest my-app`


```
pnpm -v
9.12.1

node -v
v20.18.0

OS: macOS 15.0.1
CPU: M1 Pro
(However, my friend with x86 cpu and ubuntu has the same issue)

Browsers tested:  Chrome 129.0.6668.90 and Safari

```

Maybe the issue could be `pnpm`? I cannot test this theory right now with regular `npm`.

PS. 0.4.13 works and it is looking really good!

**Comment by matlin** [comment]
The latest version of `@triplit/client` (0.5.6) should fix the issue you discovered. Thanks for letting us know!
