### ISSUE TITLE
Request: addative query builder api

### ISSUE THREAD

**Issue by wernst** [aspen-cloud/triplit#35]
Currently the query builder will overwrite values if the same method is used twice. For example `client.query('todos').where(['completed', '=', true]).where('author', '=', 'alice')` will just include the second where clause. An api like this could be preferred to many filter tuples in a single `where` statement, and also lets you define a base query with a filter in a variable then append to the where clause later.

There are some complicated edits you could make to a query's filters if the filter is deep and complex (ie deep ands / ors), so we'd need to figure out if/how the api would handle that.

**Comment by matlin** [comment]
This is now possible!
