### ISSUE TITLE
Add tools to aid with seeding the db with data

### ISSUE THREAD

**Issue by armincerf** [aspen-cloud/triplit#37]
Just jotting down some ideas here, am happy to edit this issue to refine/exclude anything you think shouldn't be in scope for this project.

- Import data from file via the console (csv/json etc)
- Import via cli
- Add seed files in whatever format to a folder on the machine hosting the server, on startup the server applies those transactions if they are new (ala the many tools available for RDMS systems)

**Comment by pbohlman** [comment]
We just added a `triplit seed` command that can push data to a remote Triplit db via the CLI. At the moment you define the seed in Typescript, but we plan on using this as the building block for csv/json seeds. Documented here https://www.triplit.dev/docs/guides/seeding.

**Comment by matlin** [comment]
Closing this for now, feel free to open a new issue for any specific seed features if you find anything missing.
