### ISSUE TITLE
chat template: `Missing required params: [token]. Skipping sync connection.`

### ISSUE THREAD

**Issue by threepointone** [aspen-cloud/triplit#51]
Hi folks! I'm trying to setup the chat example locally on my machine. I followed all the steps in the README, including making a github app and filling in the details in .env. On running the app, I get this warning in my console: 

<img width="672" alt="image" src="https://github.com/aspen-cloud/triplit/assets/18808/327a37cc-a112-47a8-aba8-a507b5891a30">

And in the triplit terminal, I see this: 
<img width="739" alt="image" src="https://github.com/aspen-cloud/triplit/assets/18808/7159428d-67af-4acf-bf4a-5b322997055e">

Because of which (I think) I'm not seeing any syncing across browsers. Do you folks have any pointers for how I can get this working? Thank you!

**Comment by wernst** [comment]
Hi @threepointone , thanks for the heads up! Looks like this may have been addressed [here](https://github.com/aspen-cloud/triplit/pull/50) but hasnt been released. We'll try to get that released ASAP.

For now in your .env can you try updating `TRIPLIT_JWT_SECRET` to the value you have in `NEXTAUTH_SECRET`? If that doesn't resolve the issue let me know.

**Comment by wernst** [comment]
We just ran a release, so you can also update the Triplit packages used in the app to their latest versions. Going to close for now, but if this issue persists let me know and we can reopen it.

**Comment by threepointone** [comment]
Looks like that fixed it, thank you so much!
